### ISSUE TITLE
Question: Resources on CI/distribution

### ISSUE THREAD

**Issue by zarko-tg** [tomwyr/pinger#1]
Hi there, it seems you've done a really good job, the app is quite nice.
I was wondering if you know of any resources (like a blog post) on the GitHub Actions CI / Fastlane / flavors / lanes setup for a Flutter project such as yours.
Best regards

**Comment by tomwyr** [comment]
Hi and thank you, I appreciate it!
To be honest, I didn't use a single blog post that would present how to set it up from the beginning to the end or anything like that. It was a mix of several articles, my previous knowledge and quite a lot of tries and issues fixing until it finally worked properly.

I'll try to find some articles that were somehow helpful and useful and give you an update here.

**Comment by zarko-tg** [comment]
Yeah, I've been through that in another context (Ionic), setting a proper release process is far from trivial. What you've done can be a solid inspiration, given that it's more or less fully streamlined / automated i.e. a full solution. I can only applaud your work.

Btw. I bumped into this just today:
https://medium.com/flutter-community/automating-flutter-publishing-with-github-actions-firebase-app-distribution-cc80dec638de

**Comment by tomwyr** [comment]
https://roszkowski.dev/2019/flutter-flavors/
This article presents really well how to setup flavors (I find iOS part especially useful).

https://docs.fastlane.tools/actions/match/ + https://codesigning.guide
I use match action for iOS code signing.

https://docs.fastlane.tools/best-practices/continuous-integration/
There are possible issues with using Fastlane from remote CI (mostly 2 factor authentication).

https://medium.com/better-programming/ci-cd-for-flutter-apps-using-github-actions-b833f8f7aac
This one presents imo pretty well how to setup GitHub actions for a Flutter project. The only difference here is that I use Fastlane for iOS codesigning and publishing apps to stores.

**Comment by zarko-tg** [comment]
Very good, thanks!

**Comment by tomwyr** [comment]
I'd say that setting up CI process was the most painful part of creating this project. Right now it's almost fully automated, I couldn't find a way to skip 2 factor authentication when publishing app to AppStore. Every time I want to publish new version of the app, I need to refresh Apple login session on my local machine and update session token secret on GitHub.

Articles that I mentioned in my previous comment may not contain all the informations needed to properly set it up. If you ran into some troubles let me know in a comment or in some other way, I'll try to help as I know how painful it can be.
