### ISSUE TITLE
null safety

### ISSUE THREAD

**Issue by ghost** [tomwyr/pinger#2]
hi @tomwyr ,

Hope you are all well !

I was wondering if you could migrate the projet to null-safety ?

Cheers,
Luc

**Comment by tomwyr** [comment]
Hi there, Luc

I guess it wouldn't be too much hassle to do that, I'll think about it. 
Can I ask you what is the motivation behind asking me for migrating it?

**Comment by ghost** [comment]
Juts because I use the latest version of flutter/dart and it is not allowing anymore to sound-null-safety and To keep the project up to data as we can add several monitoring features too :-)

**Comment by tomwyr** [comment]
Thanks!
I've already started working on the migration and will link it here once I push my changes to GH.

**Comment by ghost** [comment]
awesome :-)

**Comment by ghost** [comment]
any luck ? I tried and it is complicated with freezed. If you succeed, I would be more than happy to read how you didi it :-)

**Comment by tomwyr** [comment]
@lucmichalski I've pushed my so far changes. Most of the code has been migrated but there's still few things I'd like to look into (e.g. there are many exclamation marks inserted automatically by the migration tool).
