### ISSUE TITLE
I want the permission to use part of your project 

### ISSUE THREAD

**Issue by DevAloshe** [tomwyr/pinger#4]
hi sir, I'm kindly asking your permission to use part of your project in my commercial project

**Comment by tomwyr** [comment]
Hi. The project uses the MIT license which means you can freely use it for your commercial project too. See the full license [here](https://github.com/tomwyr/pinger/blob/master/LICENSE). The requirement is, however, you add a license note in your software (e.g. using the [license page widget](https://api.flutter.dev/flutter/material/showLicensePage.html)). 
Out of curiosity, what part of the application do you plan using in your project?

**Comment by DevAloshe** [comment]
Thank you sir, The part I want to use is the ping details screen <3 its amazing thank for making such project
